/**
 * Access layer for content migrated from the live WordPress site.
 *
 * The data is generated by `migration/transform.py` into
 * `src/data/wordpress/content.json` — each entry is a page or post with its
 * route, title, date, excerpt, featured image, categories, and the rewritten
 * (fully localized) HTML body.
 */
import content from '@/data/wordpress/content.json'

export type WordPressEntry = {
  type: 'page' | 'post'
  id: number
  slug: string
  route: string
  title: string
  date: string | null
  modified: string | null
  excerpt: string
  html: string
  featuredImage: string | null
  categories: string[]
  parent: number
  order: number
}

const entries = content as WordPressEntry[]

/** Front page (route "/"). */
export function getHome(): WordPressEntry | undefined {
  return entries.find((e) => e.route === '/')
}

/** All migrated pages except the front page. */
export function getPages(): WordPressEntry[] {
  return entries.filter((e) => e.type === 'page' && e.route !== '/')
}

/** All migrated blog posts/articles, newest first. */
export function getPosts(): WordPressEntry[] {
  return entries
    .filter((e) => e.type === 'post')
    .sort((a, b) => (b.date || '').localeCompare(a.date || ''))
}

/** Look up a single page by its slug (the segment after "/"). */
export function getPageBySlug(slug: string): WordPressEntry | undefined {
  return entries.find((e) => e.type === 'page' && e.slug === slug && e.route !== '/')
}

/** Look up a single post by slug. */
export function getPostBySlug(slug: string): WordPressEntry | undefined {
  return entries.find((e) => e.type === 'post' && e.slug === slug)
}
