// AUTO-GENERATED by scripts/extract-pdf-content.mjs — do not edit by hand.
// Re-run `npm run extract:docs` to regenerate.
import type { ContentBlock } from '@/components/DocumentContent'
import doc0 from './back-to-school-saying.json'
import doc1 from './draft-model-k12-micromobility-policy.json'
import doc2 from './emmas-letter.json'
import doc3 from './low-speed-vehicle-fact-sheet.json'
import doc4 from './my-healthy-teacher.json'
import doc5 from './powered-personal-transportation-devices.json'
import doc6 from './ride-smart-stay-safe.json'
import doc7 from './safe-kids-helmet-fit-test.json'
import doc8 from './summary-2024-25-plan-2025-2026.json'
import doc9 from './vegetable-contest-2026-27.json'

export type DocumentContentJson = {
  slug: string
  title: string
  source: 'text' | 'ocr'
  blocks: ContentBlock[]
  plain: string
}

/** Extracted document content, keyed by document slug. */
export const DOCUMENT_CONTENT: Record<string, DocumentContentJson> = {
  'back-to-school-saying': doc0 as DocumentContentJson,
  'draft-model-k12-micromobility-policy': doc1 as DocumentContentJson,
  'emmas-letter': doc2 as DocumentContentJson,
  'low-speed-vehicle-fact-sheet': doc3 as DocumentContentJson,
  'my-healthy-teacher': doc4 as DocumentContentJson,
  'powered-personal-transportation-devices': doc5 as DocumentContentJson,
  'ride-smart-stay-safe': doc6 as DocumentContentJson,
  'safe-kids-helmet-fit-test': doc7 as DocumentContentJson,
  'summary-2024-25-plan-2025-2026': doc8 as DocumentContentJson,
  'vegetable-contest-2026-27': doc9 as DocumentContentJson,
}
